// mock数据，实际使用时需要从后端获取
export const foodLists = [
    // 蔬菜类
    {
        type:"蔬菜类",
        headText: "水煮青菜",
        subText: "青菜、生姜、蒜、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "炒空心菜",
        subText: "空心菜、蒜、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "凉拌黄瓜",
        subText: "黄瓜、蒜泥、醋、盐、香油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "清炒菠菜",
        subText: "菠菜、蒜、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "油焖茄子",
        subText: "茄子、蒜、生抽、老抽、糖、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "蒜蓉西兰花",
        subText: "西兰花、蒜、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "地三鲜",
        subText: "茄子、土豆、青椒、蒜、生抽、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "干锅花菜",
        subText: "花菜、五花肉、蒜、干辣椒、生抽、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "酸辣土豆丝",
        subText: "土豆、醋、辣椒、蒜、盐、食用油",
        imgUrl: "../../static/index/vegetable.png",
    },
    {
        type:"蔬菜类",
        headText: "西红柿炒鸡蛋",
        subText: "西红柿、鸡蛋、盐、食用油、葱",
        imgUrl: "../../static/index/vegetable.png",
    },
    // 汤类
    {
        type:"汤类",
        headText: "番茄鸡蛋汤",
        subText: "番茄、鸡蛋、盐、食用油、葱",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "紫菜蛋花汤",
        subText: "紫菜、鸡蛋、盐、食用油、葱",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "蘑菇鸡肉汤",
        subText: "蘑菇、鸡肉、盐、食用油、姜",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "冬瓜排骨汤",
        subText: "冬瓜、排骨、盐、食用油、姜",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "酸辣汤",
        subText: "豆腐、木耳、鸡蛋、醋、辣椒、盐、食用油",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "南瓜浓汤",
        subText: "南瓜、牛奶、盐、食用油",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "玉米排骨汤",
        subText: "玉米、排骨、盐、食用油、姜",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "海带豆腐汤",
        subText: "海带、豆腐、盐、食用油、葱",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "虫草花炖鸡汤",
        subText: "虫草花、鸡肉、盐、食用油、姜",
        imgUrl: "../../static/index/soup.png",
    },
    {
        type:"汤类",
        headText: "山药排骨汤",
        subText: "山药、排骨、盐、食用油、姜",
        imgUrl: "../../static/index/soup.png",
    },
    // 鱼类
    {
        type:"鱼类",
        headText: "清蒸鲈鱼",
        subText: "鲈鱼、姜丝、葱丝、蒸鱼豉油、食用油",
        imgUrl: "http://m.qpic.cn/psc?/V53WsEQ043LecN4UOjYZ2MOXMg2Kmrep/TmEUgtj9EK6.7V8ajmQrEBFRlBEaLqTGgI5YzQK9eDgy7RHmO6nk4fzpi0HqHKroX08wUy2kNH84HxJyOP.Q8yUsCD0RM2j*O5uZhB3MRNg!/b&bo=OAQiBQAAAAADBzk!&rf=viewer_4",
    },
    {
        type:"鱼类",
        headText: "红烧鲤鱼",
        subText: "鲤鱼、生抽、老抽、糖、盐、姜、葱、食用油",
        imgUrl: "../../static/index/fish.png",
    },
    {
        type:"鱼类",
        headText: "酸菜鱼",
        subText: "草鱼、酸菜、泡椒、花椒、姜、葱、食用油",
        imgUrl: "../../static/index/fish.png",
    },
    {
        type:"鱼类",
        headText: "烤三文鱼",
        subText: "三文鱼、盐、黑胡椒、橄榄油、柠檬",
        imgUrl: "../../static/index/fish.png",
    },
    {
        type:"鱼类",
        headText: "糖醋黄鱼",
        subText: "黄鱼、糖、醋、生抽、老抽、姜、葱、食用油",
        imgUrl: "../../static/index/fish.png",
    },
    {
        type:"鱼类",
        headText: "剁椒鱼头",
        subText: "鱼头、剁椒、姜、葱、蒜、食用油",
        imgUrl: "../../static/index/fish.png",
    },
    {
        type:"鱼类",
        headText: "清蒸带鱼",
        subText: "带鱼、姜丝、葱丝、蒸鱼豉油、食用油",
        imgUrl: "../../static/index/fish.png",
    },
    {
        type:"鱼类",
        headText: "红烧鲳鱼",
        subText: "鲳鱼、生抽、老抽、糖、盐、姜、葱、食用油",
        imgUrl: "../../static/index/fish.png",
    },
    // 肉类
    {
        type: "肉类",
        headText: "红烧肉",
        subText: "五花肉、生抽、老抽、糖、姜、葱、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "糖醋排骨",
        subText: "排骨、糖、醋、生抽、姜、葱、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "孜然羊肉",
        subText: "羊肉、孜然粉、辣椒粉、盐、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "黑椒牛排",
        subText: "牛排、黑胡椒、盐、食用油、黄油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "回锅肉",
        subText: "五花肉、豆瓣酱、蒜苗、姜、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "东坡肉",
        subText: "五花肉、生抽、老抽、糖、姜、葱、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "粉蒸肉",
        subText: "五花肉、米粉、生抽、老抽、盐、姜、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "酱牛肉",
        subText: "牛肉、生抽、老抽、糖、盐、姜、葱、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    {
        type: "肉类",
        headText: "宫保鸡丁",
        subText: "鸡胸肉、花生米、干辣椒、花椒、生抽、糖、盐、食用油",
        imgUrl: "../../static/index/meat.png",
    },
    // 海鲜类
    {
        type: "海鲜类",
        headText: "蒜蓉粉丝蒸扇贝",
        subText: "扇贝、粉丝、蒜泥、蒸鱼豉油、食用油",
        imgUrl: "../../static/index/seafood.png",
    },
    {
        type: "海鲜类",
        headText: "白灼虾",
        subText: "鲜虾、姜、葱、料酒、盐",
        imgUrl: "../../static/index/seafood.png",
    },
    {
        type: "海鲜类",
        headText: "香辣蟹",
        subText: "螃蟹、干辣椒、花椒、姜、葱、蒜、食用油",
        imgUrl: "../../static/index/seafood.png",
    },
    {
        type: "海鲜类",
        headText: "清蒸龙虾",
        subText: "龙虾、姜丝、葱丝、蒸鱼豉油、食用油",
        imgUrl: "../../static/index/seafood.png",
    },
    {
        type: "海鲜类",
        headText: "红烧鲍鱼",
        subText: "鲍鱼、生抽、老抽、糖、姜、葱、食用油",
        imgUrl: "../../static/index/seafood.png",
    },
    {
        type: "海鲜类",
        headText: "椒盐皮皮虾",
        subText: "皮皮虾、椒盐、食用油、葱、姜",
        imgUrl: "../../static/index/seafood.png",
    },
    {
        type: "海鲜类",
        headText: "清蒸石斑鱼",
        subText: "石斑鱼、姜丝、葱丝、蒸鱼豉油、食用油",
        imgUrl: "../../static/index/seafood.png",
    },
    {
        type: "海鲜类",
        headText: "蒜蓉生蚝",
        subText: "生蚝、蒜泥、蒸鱼豉油、食用油",
        imgUrl: "../../static/index/seafood.png",
    },
    // 主食类
    {
        type: "主食类",
        headText: "扬州炒饭",
        subText: "米饭、鸡蛋、火腿、豌豆、胡萝卜、盐、食用油",
        imgUrl: "../../static/index/food.png",
    },
    {
        type: "主食类",
        headText: "北京炸酱面",
        subText: "面条、黄豆酱、肉末、黄瓜丝、黄豆芽、食用油",
        imgUrl: "../../static/index/food.png",
    },
    {
        type: "主食类",
        headText: "四川担担面",
        subText: "面条、花生酱、辣椒油、花椒油、肉末、葱花、食用油",
        imgUrl: "../../static/index/food.png",
    },
    {
        type: "主食类",
        headText: "广东肠粉",
        subText: "米粉、猪肉、葱花、生抽、食用油",
        imgUrl: "../../static/index/food.png",
    },
    {
        type: "主食类",
        headText: "兰州拉面",
        subText: "面粉、牛肉、香菜、葱花、辣椒油、牛肉汤",
        imgUrl: "../../static/index/food.png",
    },
    {
        type: "主食类",
        headText: "炒河粉",
        subText: "河粉、牛肉、豆芽、韭菜、生抽、老抽、食用油",
        imgUrl: "../../static/index/food.png",
    },
    {
        type: "主食类",
        headText: "肉夹馍",
        subText: "馍、猪肉、青椒、香菜、生抽、老抽、食用油",
        imgUrl: "../../static/index/food.png",
    },
    {
        type: "主食类",
        headText: "热干面",
        subText: "面条、芝麻酱、葱花、酸豆角、食用油",
        imgUrl: "../../static/index/food.png",
    },
    // 甜品类
    {
        type: "甜品类",
        headText: "南瓜吐司",
        subText: "高筋面粉、南瓜泥、牛奶、鸡蛋、酵母、糖、盐、黄油",
        imgUrl: "http://m.qpic.cn/psc?/V53WsEQ043LecN4UOjYZ2MOXMg2Kmrep/TmEUgtj9EK6.7V8ajmQrEDCDLSF73oiKNB*o.JFtP*7ZT0ZpLZDQTfvNmNgbk.BoixwWTQLiRgm.5G0iCAfIbefybX7tK4XwZSJY1QejjvA!/b&bo=*AT8BPwE*AQHJwY!&rf=viewer_4",
    },
    {
        type: "甜品类",
        headText: "南瓜软欧包",
        subText: "高筋面粉、南瓜泥、水、酵母、盐、糖、黄油、黑芝麻（可选）",
        imgUrl: "http://m.qpic.cn/psc?/V53WsEQ043LecN4UOjYZ2MOXMg2Kmrep/TmEUgtj9EK6.7V8ajmQrEPCZdXIbh02BtmDiqop0gFHcZJ6mbEx4Q4.RphVMBKiRvE8vjwvJQbt1hAESpEdtB3hO8GVo4GNmF5tIpIteA94!/b&bo=qgQ4BAAAAAADB7A!&rf=viewer_4",
    },
    {
        type: "甜品类",
        headText: "花苞朵朵包",
        subText: "高筋面粉、低筋面粉、牛奶、鸡蛋、酵母、糖、盐、黄油、可可粉（或食用色素）",
        imgUrl: "http://m.qpic.cn/psc?/V53WsEQ043LecN4UOjYZ2MOXMg2Kmrep/TmEUgtj9EK6.7V8ajmQrEOx7N0mB7CbsYXwVMM3yhOrFOJ2sJrdEPQW4AACuo3la1BzBHN4txC*TLe64UvzMySrgx1DIERZPLVcZ4qJg.w4!/b&bo=IAQLBAAAAAADBwk!&rf=viewer_4",
    },
    // 豆制品类
    {
        type: "豆制品类",
        headText: "香干炒肉片",
        subText: "香干、猪肉（切片）、青蒜、姜、食用油、盐、生抽、料酒、白糖",
        imgUrl: "../../static/index/bean.png",
    },
]